fix for laggy diagonal movement
edubart/otclient pull request #1108
Opened 2020-08-31 18:30 UTC by vfjpl

2020-09-02 18:20 UTC, vfjpl commented
@diath any feedback?

2020-09-06 02:50 UTC, 4drik commented
There are only 2 active reviewers, @diath & @iryont, so we need to wait for them.

2020-09-16 10:00 UTC, vfjpl commented
@diath What do you think?

2020-09-20 12:54 UTC, diath requested changes

2020-09-20 12:54 UTC, diath commented on src/client/creature.cpp
> +    int totalPixelsWalked = std::min<int>((m_walkTimer.ticksElapsed() * 32) / stepDuration, 32);
This could result in division by zero when stepDuration is 0.

2020-09-23 17:12 UTC, vfjpl commented on src/client/creature.cpp
> +    int totalPixelsWalked = std::min<int>((m_walkTimer.ticksElapsed() * 32) / stepDuration, 32);
Division by zero was also there before :)
I'm not sure if it it better to set totalPixelsWalked to 0 or 32 when stepDuration is zero... As that mean that creature is infinity fast or not moving at all? I didn't encounter anything that returned 0 so I'm not sure.

2020-09-24 15:55 UTC, diath commented on src/client/creature.cpp
> +    int totalPixelsWalked = std::min<int>((m_walkTimer.ticksElapsed() * 32) / stepDuration, 32);
There was no division by zero before because it was dividing by a zero float which has a well defined behavior for it. I guess it could maybe happen with misconfigured monsters on the server side? I vaguely recall encountering something like this. I suppose we can just do something like this:
```cpp
    int duration = getStepDuration();
    int walkTicksPerPixel = std::max<int>(duration / Otc::TILE_PIXELS, 1);
    int totalPixelsWalked = std::min<int>(m_walkTimer.ticksElapsed() / walkTicksPerPixel, Otc::TILE_PIXELS);```

2020-09-24 20:38 UTC, vfjpl commented on src/client/creature.cpp
> +    int totalPixelsWalked = std::min<int>((m_walkTimer.ticksElapsed() * 32) / stepDuration, 32);
Division by float zero and then casting that to int results in -2147483648 for me.
I don't know how it was behaving before.
Anyway If getStepDuration indeed return 0 then walk will be terminated in
```
    // terminate walk
    if(m_walking && m_walkTimer.ticksElapsed() >= getStepDuration())
        terminateWalk();
```
So maybe we should end walk earlier?
or I prefer something like this:
`    int totalPixelsWalked = stepDuration ? std::min<int>((m_walkTimer.ticksElapsed() * 32) / stepDuration, 32) : 0;`

2020-10-05 18:34 UTC, diath commented
I'd prefer if the `vector` to `deque` and timer changes were a separate PR. Also if you don't mind can we replace the `32`s in the movement code with `Otc::TILE_PIXELS`?

2020-10-07 01:14 UTC, merged