prepare bitmapfont for unicode support
edubart/otclient pull request #1129
Opened 2021-03-24 20:29 UTC by vfjpl

2021-03-26 20:27 UTC, vfjpl commented
@diath This PR cleans up bitmapfont module. Even if we don't succeed in adding unicode support, those changes are still valuable.
Please review

2021-03-26 20:48 UTC, diath requested changes

2021-03-26 20:48 UTC, diath commented on src/framework/graphics/bitmapfont.cpp
> +
Any reason these are moved from function scope to an anonymous namespace if they're not used across functions?

2021-03-26 20:48 UTC, diath commented on src/framework/graphics/bitmapfont.cpp
> +    line.pop_back();
This could result in UB if `wrapText` is called in on an empty string, it should probably be:
```cpp
if (!line.empty() {
    line.pop_back();
}
```

2021-03-26 21:22 UTC, vfjpl commented on src/framework/graphics/bitmapfont.cpp
> +
To avoid overhead of checking if we already initialized static variable every time the function is called. It's pretty small but the comment said that we use static for performance reasons so I thought we can improve it further a little bit :P
https://en.cppreference.com/w/cpp/language/storage_duration#Static_local_variables

2021-03-26 21:43 UTC, vfjpl commented on src/framework/graphics/bitmapfont.cpp
> +    line.pop_back();
I think we will get one empty string in `wordsSplit`.

http://boost.2283326.n4.nabble.com/Result-of-boost-split-against-empty-string-changed-in-post-1-45-release-td4631147.html
https://stackoverflow.com/questions/46540255/boostsplit-pushes-an-empty-string-to-the-vector-even-with-token-compress-on

2021-03-26 21:53 UTC, diath commented on src/framework/graphics/bitmapfont.cpp
> +
It looks like it's not really applicable in ST environment as rearranging the things produces the same assembly (at least in our case) however it seems like the C++ Guidelines say that anonymous namespaces should be the preferred method of dealing with things like that so I guess we can keep the change.

2021-03-26 22:22 UTC, diath commented on src/framework/graphics/bitmapfont.cpp
> +    line.pop_back();
Maybe in that case we could skip all the code if the result is an empty string anyway and just add the following at the top of the function:
```cpp
    if (text.empty()) {
        return {};
    }
```

2021-03-27 01:56 UTC, vfjpl commented on src/framework/graphics/bitmapfont.cpp
> +    line.pop_back();
wouldn't that disable NRVO?

2021-03-27 12:05 UTC, vfjpl commented on src/framework/graphics/bitmapfont.cpp
> +    line.pop_back();
That change would be pessimising normal "non empty string" to improve edge case.

I also don't like that we always add space and then remove it.

2021-03-27 15:51 UTC, diath commented on src/framework/graphics/bitmapfont.cpp
> +    line.pop_back();
That would just trade an NRVO for an RVO without needlessly executing the entire function. The overhead of checking for an empty string is insignificant although I don't think the current implementation poses any significant overhead either, I just thought it would be logically more correct to just handle an empty string instead of adding and removing the space.

2021-03-27 20:16 UTC, vfjpl commented
@diath ok you have to help me. Which one do you prefer?
``` c++
    // compose lines
    std::string line(words[0]);
    for(uint i = 1; i < words.size(); ++i)
    {
        std::string& word = words[i];

        line.push_back(' ');
        uint lineSize = line.size();
        line.append(word);

        if(calculateTextRectSize(line).width() > maxWidth)
        {
            line.resize(lineSize);
            line.back() = '\n';
            outText.append(line);
            line.assign(word);
        }
    }
    outText.append(line);
```
``` c++
    // compose lines
    std::string line;
    for(const auto& word: words)
    {
        auto lineSize = line.size();
        line.append(word);

        if(calculateTextRectSize(line).width() > maxWidth)
        {
            if(lineSize)
            {
                line.resize(lineSize);
                line.back() = '\n';
                outText.append(line);
                line.assign(word);
            }
        }

        line.push_back(' ');
    }
    line.pop_back();
    outText.append(line);
```

2021-03-27 20:30 UTC, diath commented
I'm not sure, the second one looks cleaner but I think you could merge both conditions and first check the `lineSize` so that it does not call `calculateTextRectSize` if not needed:
```cpp
if (lineSize > 0 && calculateTextRectSize(line).width() > maxWidth) {
	// ...
}
```

2021-03-27 21:02 UTC, vfjpl commented
lineSize > 0 only is there to make it so the first pass will do nothing. Otherwise we will get empty first line if first word size is still > than maxWidth. Which itself can only happen when we have space for less than two characters because we will always get at least char + '-' from breaking huge words above.

2021-03-28 17:52 UTC, vfjpl commented on src/framework/graphics/bitmapfont.cpp
> +
@diath How did you tested the assembly? for me it is different https://godbolt.org/z/4Mn7zMPrK

2021-03-29 20:28 UTC, vfjpl commented
@diath OK I have fixed the empty first line case. And also the adding and removing space that annoyed us bought. The line composing algorithm now build line in place instead on creating new string every loop iteration so it should be much faster.

2021-03-29 23:35 UTC, diath approved these changes
Looks fine, do you want me to merge this as-is?

2021-03-30 09:19 UTC, vfjpl commented
@diath Ok now you can merge. Apparently auto makes a copy if your function returns reference and if you don't specify that you want a ref… :O

2021-03-30 15:03 UTC, merged