Greeting npc on left click
edubart/otclient pull request #1150
Opened 2021-05-17 21:07 UTC by alfuveam

- [x] Option to choosen a max distance to talk him
`maxDistanceToGreetingNpc = 3`

- [x] Table with greetings words
`focusGreetWords = {"hi", "hello"}`

- [x] Random the words
`g_game.talk(focusGreetWords[math.random(1, #focusGreetWords)])`

- [x] Change a right click option on npc, attack option to talk option.

     [https://github.com/edubart/otclient/compare/master...alfuveam:greeting_npc_hi?expand=1#diff-1b975e904a1c9756dc22f83fbc9884012958e3c3f158bc081aaa6c49dfa2f585L557-R569](url)

2021-05-18 07:40 UTC, marmichalski requested changes

2021-05-18 07:40 UTC, marmichalski commented on modules/game_battle/battle.lua
> +      if self.creature:isNpc() then
IMHO this behaviour should also be configurable through a checkbox in options. There might be servers that allows attacking an NPC.

2021-05-18 07:40 UTC, marmichalski commented on modules/game_interface/gameinterface.lua
> +        if creatureThing:getPosition().z == localPosition.z then
Spacing seems to be off.

2021-05-18 07:40 UTC, marmichalski commented on modules/game_interface/gameinterface.lua
> +  end
This does not seem to be right. Won't this trigger greeting by clicking any mouse button on any NPC (different floor level [pos.z])?

This should probably be implemented at those branches in the above checks (classic/non-classic controls):
```
 elseif creatureThing and creatureThing:getPosition().z == autoWalkPos.z
```

2021-05-18 07:40 UTC, marmichalski commented on modules/game_interface/gameinterface.lua
> +function checkMaxDistanceToGreetingNpc(creaturePlayer, creatureNpc)
This is not really a `check` when it triggers an action, is it? :)

2021-08-25 17:24 UTC, closed without merging

2026-01-13 11:34 UTC, gianpeiter commented
Have you made any progress in this role?